[package]
name = "tiny-substrate-client"
version = "0.1.0"
authors = ["Ozaki Yoichi <zak@nli.ics.keio.ac.jp>"]
edition = "2018"

[dependencies]
websocket = "0.22.0"
serde_json = "1.0"
serde = "1.0.88"
colored = "1.7"